spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8070
  metrics:
    prometheus:
      enabled: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    de.codecentric.boot.admin.client.registration: debug